api:
  gateway:
    url: http://localhost:8080 # docelowo wstawic coś "produkcyjnego"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # producyjnie byłoby coś innego