spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
