spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:demoorder
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
order:
  api:
    endpoints:
      book-price-endpoint: /api/v1/books/{bookId}/price